AcmeStorageUnitRental/Models/StorageUnit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AcmeStorageUnitRental.Models
{
    public class StorageUnit
    {
        public int UnitNumber { get; set; }
        public string Size { get; set; }
        public string MonthlyCost { get; set; }
        public bool CurrentlyRented { get; set; }

    }
}

AcmeStorageUnitRental/Controllers/HomeController.cs
using AcmeStorageUnitRental.DataLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcmeStorageUnitRental.Controllers
{
    public class HomeController : Controller
    {

 

 
        public HomeController()
        {
          
        }


        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

AcmeStorageUnitRental/Controllers/StorageUnitsController.cs
using AcmeStorageUnitRental.DataLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AcmeStorageUnitRental.Controllers
{
    public class StorageUnitsController : Controller
    {
        private IStorageUnitRepository _storageUnitRepository;
        public StorageUnitsController(IStorageUnitRepository storageUnitRepository)
        {
            _storageUnitRepository = storageUnitRepository;
        }
       
        public ActionResult Index()
        {
            return View(_storageUnitRepository.GetStorageUnits());
        }
       
    }
}

AcmeStorageUnitRental/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Welcome";
}

<h2>Welcome to Acme Storage</h2>

AcmeStorageUnitRental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Acme Storage</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Acme Storage", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Storage units", "Index", "StorageUnits", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Acme Storage</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

AcmeStorageUnitRental/Views/StorageUnits/Index.cshtml
@using AcmeStorageUnitRental.Models
@model List<StorageUnit>
@{
    ViewBag.Title = "Storage Units";
    

}

<h2>StorageUnits</h2>

<div>Units</div>
<table width="600" border="1" >
    <thead>
        <tr>
            <td  align="center">Unit Number</td>
            <td align="center">Size</td>
            <td align="center">Monthly Rate</td>
            <td align="center">Rented</td>
            <td  align="center">Options</td>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td width="90" align="center">
                @Html.DisplayFor(modelItem => item.UnitNumber)
            </td>
            <td width="80"  align="center">
                @Html.DisplayFor(modelItem => item.Size)
            </td width="200">
            <td width="95">
                @Html.DisplayFor(modelItem => item.MonthlyCost)
            </td>
            <td width="80" align="center">
                @Html.DisplayFor(modelItem => item.CurrentlyRented)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.UnitNumber }) |
                @Html.ActionLink("Details", "Details", new { id = item.UnitNumber }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.UnitNumber })
            </td>
        </tr>
    }

</table>